### ISSUE TITLE
PNG thumbnail error

### ISSUE THREAD

**Issue by HJulio** [silentsokolov/flask-thumbnails#11]
If you try to thumbnail a PNG (with alpha channel) you get an Pillow error:

```
    File ".../python3.6/site-packages/PIL/JpegImagePlugin.py", line 604, in _save

    raise IOError("cannot write mode %s as JPEG" % im.mode)

    OSError: cannot write mode RGBA as JPEG
```

**Comment by silentsokolov** [comment]
Please, send the full traceback of the error and picture (whenever possible).

**Comment by eddwinn** [comment]
Issue still relevant with newest pull

**Comment by silentsokolov** [comment]
Please, send the full traceback

**Comment by HJulio** [comment]
Sorry, was out.


Traceback (most recent call last):
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/hjulio/Proyectos/portfolio_raquel/app/views.py", line 40, in entrada
    return render_template('entrada.html', entrada=entrada)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/hjulio/Proyectos/portfolio_raquel/app/templates/entrada.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/Users/hjulio/Proyectos/portfolio_raquel/app/templates/layout.html", line 28, in top-level template code
    {% block content %} {% endblock %}
  File "/Users/hjulio/Proyectos/portfolio_raquel/app/templates/entrada.html", line 26, in block "content"
    {% include "/entradas/noticia.html" %}
  File "/Users/hjulio/Proyectos/portfolio_raquel/app/templates/entradas/noticia.html", line 24, in top-level template code
    <img src="{{ entrada.img | thumbnail('350x350') }}" class="img-responsive img-header" alt="">
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask_thumbnails/__init__.py", line 119, in get_thumbnail
    raw_data = self.get_raw_data(image, **options)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/flask_thumbnails/__init__.py", line 131, in get_raw_data
    image.save(_file, **data)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/PIL/Image.py", line 1893, in save
    save_handler(self, fp, filename)
  File "/Users/hjulio/Proyectos/portfolio_raquel/env/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 604, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG


The img can be any transparent png:
![gabumon](https://user-images.githubusercontent.com/13355170/29959173-6ccb5ce8-8ef6-11e7-8f2b-751a34e9654b.png)

You can solve it using the `THUMBNAIL_DEFAUL_FORMAT = 'PNG'` option

**Comment by silentsokolov** [comment]
Update to 1.0.3, and tell me results.

**Comment by HJulio** [comment]
@silentsokolov it work! now png files are cached with new pngs and everything work fine

thank you

**Comment by silentsokolov** [comment]
thank you
